name: Lint and format

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environemnt
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run Prettier format Checkout
        run: npm format:check
